export const ADD_POST = 'ADD_POST'
export const POST_LOADING = 'POST_LOADING'
export const POST_FAILED = 'POST_FAILED'
export const GET_POST = 'GET_POST'
export const ADD_USER = 'ADD_USER'
export const GET_USER = 'GET_USER'
export const UPDATE_USER = 'UPDATE_USER'